
[window]
dynamic_padding = true
decorations = "None"
opacity = 0.9
blur = true
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16.0

[keyboard]
bindings = [
  { key = "M", mods = "Command|Control", action = "ToggleMaximized" }
]

[general]
import = [
    "~/.config/alacritty/gruvbox_dark.toml"
]
